---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: demowebapp
 labels:
  app: demowebapp
spec:
 replicas: 1
 selector:
  matchLabels:
   app: demowebapp
 template:
  metadata: 
   labels:
    app: demowebapp
  spec:
   containers:
   - name: demowebapp
     image: madhusrt1/kube8s:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demowebapp
spec:
  type: LoadBalancer
  selector:
    app: demowebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
